# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BodyPose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x42odyPose.proto\x12\x08\x62odypose\"\'\n\x16\x45xtractBodyPoseRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"(\n\x17\x45xtractBodyPoseResponse\x12\r\n\x05point\x18\x01 \x01(\x0c\x32\x64\n\x08\x42odyPose\x12X\n\x0f\x45xtractBodyPose\x12 .bodypose.ExtractBodyPoseRequest\x1a!.bodypose.ExtractBodyPoseResponse\"\x00\x62\x06proto3')


_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BodyPose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTRACTBODYPOSEREQUEST._serialized_start=28
  _EXTRACTBODYPOSEREQUEST._serialized_end=67
  _EXTRACTBODYPOSERESPONSE._serialized_start=69
  _EXTRACTBODYPOSERESPONSE._serialized_end=109
  _BODYPOSE._serialized_start=111
  _BODYPOSE._serialized_end=211
# @@protoc_insertion_point(module_scope)
